import 'package:injectable/injectable.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:quick_church/core/utils/kneel_logger.dart';
import '../../domain/entities/testimony.dart';
import '../../domain/repositories/i_testimony_repository.dart';

/// Supabase implementation of the Testimony repository.
@LazySingleton(as: ITestimonyRepository)
class SupabaseTestimonyRepository implements ITestimonyRepository {
  SupabaseClient get _client => Supabase.instance.client;

  String? get _userId => _client.auth.currentUser?.id;

  static const _testimoniesTable = 'testimonies';
  static const _statsTable = 'testimony_stats';

  @override
  Future<Testimony> createTestimony({
    required TestimonyType type,
    required String title,
    String? story,
    String? prayerId,
    String? prayerTitle,
    int prayerCount = 0,
    int? daysToAnswer,
    DateTime? eventDate,
    bool isPublic = false,
    String? imageUrl,
    GratitudeCategory? category,
  }) async {
    final userId = _userId;
    if (userId == null) {
      throw Exception('User not authenticated');
    }

    try {
      final testimony = Testimony(
        id: '', // Generated by Supabase
        userId: userId,
        type: type,
        title: title,
        story: story,
        prayerId: prayerId,
        prayerTitle: prayerTitle,
        prayerCount: prayerCount,
        daysToAnswer: daysToAnswer,
        eventDate: eventDate,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        isPublic: isPublic,
        imageUrl: imageUrl,
        category: category,
      );

      final response = await _client
          .from(_testimoniesTable)
          .insert(testimony.toInsertJson())
          .select()
          .single();

      final savedTestimony = Testimony.fromJson(response);

      KneelLogger.log(
        'Created testimony: ${savedTestimony.id} (${type.displayName})',
        context: 'TestimonyRepository',
      );

      return savedTestimony;
    } catch (e) {
      KneelLogger.error('TestimonyRepository.createTestimony', e);
      rethrow;
    }
  }

  @override
  Future<List<Testimony>> getTestimonies({int limit = 100}) async {
    final userId = _userId;
    if (userId == null) return [];

    try {
      final response = await _client
          .from(_testimoniesTable)
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false)
          .limit(limit);

      return (response as List)
          .map((json) => Testimony.fromJson(json as Map<String, dynamic>))
          .toList();
    } catch (e) {
      KneelLogger.error('TestimonyRepository.getTestimonies', e);
      return [];
    }
  }

  @override
  Future<List<Testimony>> getTestimoniesByType(
    TestimonyType type, {
    int limit = 50,
  }) async {
    final userId = _userId;
    if (userId == null) return [];

    try {
      final response = await _client
          .from(_testimoniesTable)
          .select()
          .eq('user_id', userId)
          .eq('type', type.dbValue)
          .order('created_at', ascending: false)
          .limit(limit);

      return (response as List)
          .map((json) => Testimony.fromJson(json as Map<String, dynamic>))
          .toList();
    } catch (e) {
      KneelLogger.error('TestimonyRepository.getTestimoniesByType', e);
      return [];
    }
  }

  @override
  Future<Testimony?> getTestimonyById(String id) async {
    try {
      final response = await _client
          .from(_testimoniesTable)
          .select()
          .eq('id', id)
          .maybeSingle();

      if (response == null) return null;
      return Testimony.fromJson(response);
    } catch (e) {
      KneelLogger.error('TestimonyRepository.getTestimonyById', e);
      return null;
    }
  }

  @override
  Future<Testimony> updateTestimony(Testimony testimony) async {
    final userId = _userId;
    if (userId == null) {
      throw Exception('User not authenticated');
    }

    try {
      final response = await _client
          .from(_testimoniesTable)
          .update(testimony.toJson())
          .eq('id', testimony.id)
          .eq('user_id', userId)
          .select()
          .single();

      final updated = Testimony.fromJson(response);

      KneelLogger.log(
        'Updated testimony: ${updated.id}',
        context: 'TestimonyRepository',
      );

      return updated;
    } catch (e) {
      KneelLogger.error('TestimonyRepository.updateTestimony', e);
      rethrow;
    }
  }

  @override
  Future<void> updatePrivacy(String id, bool isPublic) async {
    final userId = _userId;
    if (userId == null) return;

    try {
      await _client
          .from(_testimoniesTable)
          .update({
            'is_public': isPublic,
            'updated_at': DateTime.now().toUtc().toIso8601String(),
          })
          .eq('id', id)
          .eq('user_id', userId);

      KneelLogger.log(
        'Updated testimony privacy: $id -> ${isPublic ? 'public' : 'private'}',
        context: 'TestimonyRepository',
      );
    } catch (e) {
      KneelLogger.error('TestimonyRepository.updatePrivacy', e);
      rethrow;
    }
  }

  @override
  Future<void> deleteTestimony(String id) async {
    final userId = _userId;
    if (userId == null) return;

    try {
      await _client
          .from(_testimoniesTable)
          .delete()
          .eq('id', id)
          .eq('user_id', userId);

      KneelLogger.log(
        'Deleted testimony: $id',
        context: 'TestimonyRepository',
      );
    } catch (e) {
      KneelLogger.error('TestimonyRepository.deleteTestimony', e);
      rethrow;
    }
  }

  @override
  Future<List<Testimony>> getPublicTestimonies({int limit = 50}) async {
    try {
      final response = await _client
          .from(_testimoniesTable)
          .select()
          .eq('is_public', true)
          .order('created_at', ascending: false)
          .limit(limit);

      return (response as List)
          .map((json) => Testimony.fromJson(json as Map<String, dynamic>))
          .toList();
    } catch (e) {
      KneelLogger.error('TestimonyRepository.getPublicTestimonies', e);
      return [];
    }
  }

  @override
  Future<TestimonyStats> getStats() async {
    final userId = _userId;
    if (userId == null) return const TestimonyStats();

    try {
      final response = await _client
          .from(_statsTable)
          .select()
          .eq('user_id', userId)
          .maybeSingle();

      if (response == null) {
        return const TestimonyStats();
      }

      return TestimonyStats.fromJson(response);
    } catch (e) {
      KneelLogger.error('TestimonyRepository.getStats', e);
      return const TestimonyStats();
    }
  }

  @override
  Stream<List<Testimony>> watchTestimonies({int limit = 50}) {
    final userId = _userId;
    if (userId == null) {
      return Stream.value([]);
    }

    return _client
        .from(_testimoniesTable)
        .stream(primaryKey: ['id'])
        .eq('user_id', userId)
        .order('created_at', ascending: false)
        .limit(limit)
        .map((list) => list.map((json) => Testimony.fromJson(json)).toList());
  }

  @override
  Stream<TestimonyStats> watchStats() {
    final userId = _userId;
    if (userId == null) {
      return Stream.value(const TestimonyStats());
    }

    return _client
        .from(_statsTable)
        .stream(primaryKey: ['user_id'])
        .eq('user_id', userId)
        .map((list) {
          if (list.isEmpty) return const TestimonyStats();
          return TestimonyStats.fromJson(list.first);
        });
  }

  @override
  Future<void> celebrateTestimony(String id) async {
    try {
      // Increment celebration count
      await _client.rpc('increment_testimony_celebration', params: {'testimony_id': id});

      KneelLogger.log(
        'Celebrated testimony: $id',
        context: 'TestimonyRepository',
      );
    } catch (e) {
      // Fallback: direct update if RPC doesn't exist
      try {
        final current = await getTestimonyById(id);
        if (current != null) {
          await _client
              .from(_testimoniesTable)
              .update({
                'celebration_count': current.celebrationCount + 1,
              })
              .eq('id', id);
        }
      } catch (e2) {
        KneelLogger.error('TestimonyRepository.celebrateTestimony', e2);
      }
    }
  }
}
