import 'package:injectable/injectable.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:quick_church/core/utils/kneel_logger.dart';
import '../../domain/entities/focus_session.dart';
import '../../domain/repositories/i_focus_repository.dart';

/// Supabase implementation of the Focus repository.
/// Production-ready with real-time streams and optimized queries.
@LazySingleton(as: IFocusRepository)
class SupabaseFocusRepository implements IFocusRepository {
  SupabaseClient get _client => Supabase.instance.client;

  String? get _userId => _client.auth.currentUser?.id;

  /// Table names
  static const _sessionsTable = 'focus_sessions';
  static const _statsTable = 'focus_stats';
  static const _achievementsTable = 'focus_achievements';

  @override
  Future<FocusSession> saveSession({
    required FocusType type,
    int? plannedDurationMinutes,
    required int actualDurationSeconds,
    String? prayerId,
    String? prayerTitle,
    required DateTime startedAt,
    String? notes,
    required bool wasCompleted,
    bool isOpenEnded = false,
  }) async {
    final userId = _userId;
    if (userId == null) {
      throw Exception('User not authenticated');
    }

    try {
      // Calculate achievements earned in this session
      final actualMinutes = (actualDurationSeconds / 60).ceil();
      final achievements = FocusAchievement.getAchievementsFor(actualMinutes);

      // Create session object
      final session = FocusSession(
        id: '', // Will be generated by Supabase
        userId: userId,
        type: type,
        plannedDurationMinutes: plannedDurationMinutes,
        actualDurationSeconds: actualDurationSeconds,
        prayerId: prayerId,
        prayerTitle: prayerTitle,
        startedAt: startedAt,
        completedAt: DateTime.now(),
        notes: notes,
        wasCompleted: wasCompleted,
        isOpenEnded: isOpenEnded,
        achievementsEarned: achievements,
      );

      // Insert into database
      final response = await _client
          .from(_sessionsTable)
          .insert(session.toInsertJson())
          .select()
          .single();

      final savedSession = FocusSession.fromJson(response);

      // Check for new achievements and unlock them
      await _checkAndUnlockAchievements(userId, savedSession.id, actualMinutes);

      KneelLogger.log(
        'Saved focus session: ${savedSession.id} ($actualMinutes min ${type.displayName})',
        context: 'FocusRepository',
      );

      return savedSession;
    } catch (e) {
      KneelLogger.error('FocusRepository.saveSession', e);
      rethrow;
    }
  }

  /// Check for new achievements and unlock them.
  Future<void> _checkAndUnlockAchievements(
    String userId,
    String sessionId,
    int minutes,
  ) async {
    try {
      // Get currently unlocked achievements
      final unlocked = await getUnlockedAchievements();

      // Get achievements earned in this session
      final earned = FocusAchievement.getAchievementsFor(minutes);

      // Find new achievements
      final newAchievements = earned.where((a) => !unlocked.contains(a));

      // Unlock each new achievement
      for (final achievement in newAchievements) {
        await unlockAchievement(achievement, sessionId);
      }

      // Check for first session achievement
      if (!unlocked.contains(FocusAchievement.firstSession)) {
        await unlockAchievement(FocusAchievement.firstSession, sessionId);
      }
    } catch (e) {
      KneelLogger.error('FocusRepository._checkAndUnlockAchievements', e);
      // Don't rethrow - achievements are supplementary
    }
  }

  @override
  Future<List<FocusSession>> getSessions({int limit = 50}) async {
    final userId = _userId;
    if (userId == null) return [];

    try {
      final response = await _client
          .from(_sessionsTable)
          .select()
          .eq('user_id', userId)
          .order('completed_at', ascending: false)
          .limit(limit);

      return (response as List)
          .map((json) => FocusSession.fromJson(json as Map<String, dynamic>))
          .toList();
    } catch (e) {
      KneelLogger.error('FocusRepository.getSessions', e);
      return [];
    }
  }

  @override
  Future<List<FocusSession>> getSessionsInRange(
    DateTime start,
    DateTime end,
  ) async {
    final userId = _userId;
    if (userId == null) return [];

    try {
      final startDate = start.toIso8601String().split('T')[0];
      final endDate = end.toIso8601String().split('T')[0];

      final response = await _client
          .from(_sessionsTable)
          .select()
          .eq('user_id', userId)
          .gte('session_date', startDate)
          .lte('session_date', endDate)
          .order('completed_at', ascending: false);

      return (response as List)
          .map((json) => FocusSession.fromJson(json as Map<String, dynamic>))
          .toList();
    } catch (e) {
      KneelLogger.error('FocusRepository.getSessionsInRange', e);
      return [];
    }
  }

  @override
  Future<List<FocusSession>> getTodaySessions() async {
    final now = DateTime.now();
    final startOfDay = DateTime(now.year, now.month, now.day);
    final endOfDay = startOfDay.add(const Duration(days: 1));
    return getSessionsInRange(startOfDay, endOfDay);
  }

  @override
  Future<List<FocusSession>> getThisWeekSessions() async {
    final now = DateTime.now();
    final daysFromSunday = now.weekday % 7;
    final startOfWeek = DateTime(now.year, now.month, now.day)
        .subtract(Duration(days: daysFromSunday));
    final endOfWeek = startOfWeek.add(const Duration(days: 7));
    return getSessionsInRange(startOfWeek, endOfWeek);
  }

  @override
  Future<FocusStats> getStats() async {
    final userId = _userId;
    if (userId == null) return const FocusStats();

    try {
      // Get cached stats from focus_stats table
      final response = await _client
          .from(_statsTable)
          .select()
          .eq('user_id', userId)
          .maybeSingle();

      if (response == null) {
        // No stats yet, return empty
        return const FocusStats();
      }

      // Get unlocked achievements
      final achievements = await getUnlockedAchievements();

      return FocusStats.fromJson(response).copyWith(
        unlockedAchievements: achievements,
      );
    } catch (e) {
      KneelLogger.error('FocusRepository.getStats', e);
      return const FocusStats();
    }
  }

  @override
  Future<Map<DateTime, FocusDailyActivity>> getActivityHeatmap({
    int days = 365,
  }) async {
    final userId = _userId;
    if (userId == null) return {};

    try {
      final endDate = DateTime.now();
      final startDate = endDate.subtract(Duration(days: days));

      // Fetch all sessions in range
      final sessions = await getSessionsInRange(startDate, endDate);

      // Group by date
      final Map<DateTime, List<FocusSession>> grouped = {};
      for (final session in sessions) {
        final dateKey = DateTime(
          session.sessionDate.year,
          session.sessionDate.month,
          session.sessionDate.day,
        );
        grouped.putIfAbsent(dateKey, () => []).add(session);
      }

      // Convert to FocusDailyActivity
      final Map<DateTime, FocusDailyActivity> heatmap = {};
      grouped.forEach((date, daySessions) {
        heatmap[date] = FocusDailyActivity(
          date: date,
          sessionCount: daySessions.length,
          totalMinutes: daySessions.fold(0, (sum, s) => sum + s.actualMinutes),
          types: daySessions.map((s) => s.type).toSet().toList(),
        );
      });

      return heatmap;
    } catch (e) {
      KneelLogger.error('FocusRepository.getActivityHeatmap', e);
      return {};
    }
  }

  @override
  Future<Set<FocusAchievement>> getUnlockedAchievements() async {
    final userId = _userId;
    if (userId == null) return {};

    try {
      final response = await _client
          .from(_achievementsTable)
          .select('achievement_key')
          .eq('user_id', userId);

      final achievements = <FocusAchievement>{};
      for (final row in response as List) {
        final key = row['achievement_key'] as String?;
        if (key != null) {
          final achievement = FocusAchievement.fromDbKey(key);
          if (achievement != null) {
            achievements.add(achievement);
          }
        }
      }

      return achievements;
    } catch (e) {
      KneelLogger.error('FocusRepository.getUnlockedAchievements', e);
      return {};
    }
  }

  @override
  Future<void> unlockAchievement(
    FocusAchievement achievement,
    String? sessionId,
  ) async {
    final userId = _userId;
    if (userId == null) return;

    try {
      await _client.from(_achievementsTable).upsert({
        'user_id': userId,
        'achievement_key': achievement.dbKey,
        'session_id': sessionId,
        'unlocked_at': DateTime.now().toUtc().toIso8601String(),
      });

      KneelLogger.log(
        'Unlocked achievement: ${achievement.title}',
        context: 'FocusRepository',
      );
    } catch (e) {
      KneelLogger.error('FocusRepository.unlockAchievement', e);
      // Don't rethrow - achievements are supplementary
    }
  }

  @override
  Future<void> deleteSession(String sessionId) async {
    final userId = _userId;
    if (userId == null) return;

    try {
      await _client
          .from(_sessionsTable)
          .delete()
          .eq('id', sessionId)
          .eq('user_id', userId);

      KneelLogger.log(
        'Deleted focus session: $sessionId',
        context: 'FocusRepository',
      );
    } catch (e) {
      KneelLogger.error('FocusRepository.deleteSession', e);
      rethrow;
    }
  }

  @override
  Stream<List<FocusSession>> watchSessions({int limit = 20}) {
    final userId = _userId;
    if (userId == null) {
      return Stream.value([]);
    }

    return _client
        .from(_sessionsTable)
        .stream(primaryKey: ['id'])
        .eq('user_id', userId)
        .order('completed_at', ascending: false)
        .limit(limit)
        .map((list) => list
            .map((json) => FocusSession.fromJson(json))
            .toList());
  }

  @override
  Stream<FocusStats> watchStats() {
    final userId = _userId;
    if (userId == null) {
      return Stream.value(const FocusStats());
    }

    return _client
        .from(_statsTable)
        .stream(primaryKey: ['user_id'])
        .eq('user_id', userId)
        .map((list) {
          if (list.isEmpty) return const FocusStats();
          return FocusStats.fromJson(list.first);
        });
  }
}
