import 'dart:async';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:quick_church/core/utils/debug_logger.dart';
import 'package:quick_church/features/sermon/domain/entities/sermon_note.dart';
import 'package:quick_church/features/sermon/domain/entities/sermon_series.dart';
import 'package:quick_church/features/sermon/domain/repositories/i_sermon_repository.dart';
import 'package:quick_church/features/sermon/presentation/bloc/sermon_state.dart';

/// Manages the Sermon Vault state using Supabase backend.
@lazySingleton
class SermonCubit extends Cubit<SermonState> {
  final ISermonRepository _repository;
  String? _currentUserId;
  StreamSubscription? _notesSubscription;
  StreamSubscription? _seriesSubscription;

  SermonCubit(this._repository) : super(const SermonInitial());

  /// Initialize the cubit with a user ID.
  void init(String userId) {
    _currentUserId = userId;
    loadSermons();
  }

  /// Load all sermon notes and build folder structure from Supabase.
  Future<void> loadSermons() async {
    if (_currentUserId == null) {
      emit(const SermonError('User not authenticated'));
      return;
    }

    emit(const SermonLoading());

    try {
      // Fetch notes and series in parallel
      final results = await Future.wait([
        _repository.getAllNotes(_currentUserId!),
        _repository.getSeriesWithNoteCount(_currentUserId!),
      ]);

      final notes = results[0] as List<SermonNote>;
      final seriesWithCounts = results[1] as List<SermonSeriesWithCount>;

      // Build folder list
      final folders = _buildFolders(notes, seriesWithCounts);

      emit(SermonLoaded(notes: notes, folders: folders));

      // Start watching for real-time updates
      _watchNotes();
    } catch (e) {
      DebugLogger.error('SermonCubit.loadSermons', e);
      emit(SermonError('Failed to load sermons: $e'));
    }
  }

  /// Build folder list from notes and series.
  List<SermonFolder> _buildFolders(
    List<SermonNote> notes,
    List<SermonSeriesWithCount> seriesWithCounts,
  ) {
    final folders = <SermonFolder>[];

    // Add "All Sermons" folder
    folders.add(SermonFolder(
      id: null,
      name: 'All Sermons',
      noteCount: notes.length,
      isAllSermons: true,
      lastUpdated: notes.isNotEmpty ? notes.first.updatedAt : null,
    ));

    // Add series folders with counts
    for (final swc in seriesWithCounts) {
      folders.add(SermonFolder(
        id: swc.series.id,
        name: swc.series.title,
        noteCount: swc.noteCount,
        isAllSermons: false,
        lastUpdated: swc.lastNoteUpdated ?? swc.series.updatedAt,
        color: swc.series.color,
        icon: swc.series.icon,
      ));
    }

    // Add "Uncategorized" folder if there are notes without a series
    final uncategorizedCount = notes.where((n) => n.seriesId == null).length;
    if (uncategorizedCount > 0) {
      folders.add(SermonFolder(
        id: 'uncategorized',
        name: 'Uncategorized',
        noteCount: uncategorizedCount,
        isAllSermons: false,
        lastUpdated: notes
            .where((n) => n.seriesId == null)
            .map((n) => n.updatedAt)
            .reduce((a, b) => a.isAfter(b) ? a : b),
        color: '#9E9E9E',
        icon: 'inbox',
      ));
    }

    return folders;
  }

  /// Watch for real-time note updates.
  void _watchNotes() {
    _notesSubscription?.cancel();
    if (_currentUserId == null) return;

    _notesSubscription = _repository.watchNotes(_currentUserId!).listen(
      (notes) {
        final currentState = state;
        if (currentState is SermonLoaded) {
          // Rebuild folders with updated notes
          _repository.getSeriesWithNoteCount(_currentUserId!).then((series) {
            final folders = _buildFolders(notes, series);
            emit(currentState.copyWith(notes: notes, folders: folders));
          });
        }
      },
      onError: (e) {
        DebugLogger.error('SermonCubit.watchNotes', e);
      },
    );
  }

  // ============================================================================
  // SERIES OPERATIONS
  // ============================================================================

  /// Create a new series.
  Future<SermonSeries?> createSeries({
    required String title,
    String? description,
    String color = '#673AB7',
    String icon = 'folder',
  }) async {
    if (_currentUserId == null) return null;

    try {
      final series = SermonSeries(
        id: '', // Will be generated by Supabase
        userId: _currentUserId!,
        title: title,
        description: description,
        color: color,
        icon: icon,
        sortOrder: 0,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final created = await _repository.createSeries(series);
      await loadSermons(); // Refresh the list
      return created;
    } catch (e) {
      DebugLogger.error('SermonCubit.createSeries', e);
      emit(SermonError('Failed to create series: $e'));
      return null;
    }
  }

  /// Update a series.
  Future<void> updateSeries(SermonSeries series) async {
    try {
      await _repository.updateSeries(series);
      await loadSermons();
    } catch (e) {
      DebugLogger.error('SermonCubit.updateSeries', e);
      emit(SermonError('Failed to update series: $e'));
    }
  }

  /// Delete a series.
  Future<void> deleteSeries(String seriesId) async {
    try {
      await _repository.deleteSeries(seriesId);
      await loadSermons();
    } catch (e) {
      DebugLogger.error('SermonCubit.deleteSeries', e);
      emit(SermonError('Failed to delete series: $e'));
    }
  }

  /// Reorder folders (for ReorderableListView).
  void reorderFolders(int oldIndex, int newIndex) {
    final currentState = state;
    if (currentState is! SermonLoaded) return;
    if (_currentUserId == null) return;

    // Note: "All Sermons" stays at index 0
    if (oldIndex == 0 || newIndex == 0) return;

    final folders = List<SermonFolder>.from(currentState.folders);
    final folder = folders.removeAt(oldIndex);
    folders.insert(newIndex > oldIndex ? newIndex - 1 : newIndex, folder);

    emit(currentState.copyWith(folders: folders));

    // Persist reorder to Supabase
    final seriesIds = folders
        .where((f) => f.id != null && f.id != 'uncategorized' && !f.isAllSermons)
        .map((f) => f.id!)
        .toList();

    _repository.reorderSeries(_currentUserId!, seriesIds).catchError((e) {
      DebugLogger.error('SermonCubit.reorderFolders', e);
    });
  }

  // ============================================================================
  // NOTE OPERATIONS
  // ============================================================================

  /// Add or update a sermon note using upsert logic.
  Future<SermonNote?> saveNote(SermonNote note) async {
    if (_currentUserId == null) return null;

    try {
      // Ensure the note has the correct user ID
      final noteToSave = note.copyWith(userId: _currentUserId);
      final saved = await _repository.saveNote(noteToSave);
      await loadSermons();
      return saved;
    } catch (e) {
      DebugLogger.error('SermonCubit.saveNote', e);
      emit(SermonError('Failed to save sermon: $e'));
      return null;
    }
  }

  /// Legacy method for backward compatibility.
  Future<void> addSermon(SermonNote note) async {
    await saveNote(note);
  }

  /// Legacy method for backward compatibility.
  Future<void> updateSermon(SermonNote note) async {
    await saveNote(note);
  }

  /// Delete a sermon note.
  Future<void> deleteSermon(String id) async {
    try {
      await _repository.deleteNote(id);
      await loadSermons();
    } catch (e) {
      DebugLogger.error('SermonCubit.deleteSermon', e);
      emit(SermonError('Failed to delete sermon: $e'));
    }
  }

  /// Toggle pin status of a sermon note.
  Future<void> togglePin(String id) async {
    try {
      await _repository.togglePin(id);
      await loadSermons();
    } catch (e) {
      DebugLogger.error('SermonCubit.togglePin', e);
      emit(SermonError('Failed to toggle pin: $e'));
    }
  }

  // ============================================================================
  // SEARCH OPERATIONS
  // ============================================================================

  /// Global search across title, preacher, content, and verse.
  Future<void> search(String query) async {
    if (_currentUserId == null) return;

    final currentState = state;
    if (currentState is! SermonLoaded) return;

    if (query.isEmpty) {
      emit(currentState.copyWith(clearSearch: true));
      return;
    }

    try {
      final results = await _repository.search(_currentUserId!, query);
      emit(currentState.copyWith(
        searchQuery: query,
        notes: results,
      ));
    } catch (e) {
      DebugLogger.error('SermonCubit.search', e);
      // Keep current state on search error
      emit(currentState.copyWith(searchQuery: query));
    }
  }

  /// Clear search and reload all notes.
  void clearSearch() {
    final currentState = state;
    if (currentState is SermonLoaded) {
      emit(currentState.copyWith(clearSearch: true));
      loadSermons(); // Reload all notes
    }
  }

  /// Select a folder.
  void selectFolder(String? folderName) {
    final currentState = state;
    if (currentState is SermonLoaded) {
      emit(currentState.copyWith(
        selectedFolder: folderName,
        clearFolder: folderName == null,
      ));
    }
  }

  // ============================================================================
  // HELPERS
  // ============================================================================

  /// Get note by ID.
  SermonNote? getNoteById(String id) {
    final currentState = state;
    if (currentState is SermonLoaded) {
      try {
        return currentState.notes.firstWhere((n) => n.id == id);
      } catch (_) {
        return null;
      }
    }
    return null;
  }

  /// Get notes for a folder.
  List<SermonNote> getNotesForFolder(String? folderId) {
    final currentState = state;
    if (currentState is! SermonLoaded) return [];

    if (folderId == null) {
      // All Sermons
      return List.from(currentState.notes)
        ..sort((a, b) => b.sermonDate.compareTo(a.sermonDate));
    }

    if (folderId == 'uncategorized') {
      return currentState.notes
          .where((n) => n.seriesId == null)
          .toList()
        ..sort((a, b) => b.sermonDate.compareTo(a.sermonDate));
    }

    return currentState.notes
        .where((n) => n.seriesId == folderId)
        .toList()
      ..sort((a, b) => b.sermonDate.compareTo(a.sermonDate));
  }

  /// Get folder by name.
  SermonFolder? getFolderByName(String name) {
    final currentState = state;
    if (currentState is SermonLoaded) {
      try {
        return currentState.folders.firstWhere((f) => f.name == name);
      } catch (_) {
        return null;
      }
    }
    return null;
  }

  /// Get all series for dropdown selection.
  List<SermonSeries> getAllSeries() {
    final currentState = state;
    if (currentState is! SermonLoaded) return [];

    return currentState.folders
        .where((f) => f.id != null && f.id != 'uncategorized' && !f.isAllSermons)
        .map((f) => SermonSeries(
              id: f.id!,
              userId: _currentUserId ?? '',
              title: f.name,
              color: f.color,
              icon: f.icon,
              createdAt: DateTime.now(),
              updatedAt: f.lastUpdated ?? DateTime.now(),
            ))
        .toList();
  }

  /// Clear state (on logout).
  void clear() {
    _notesSubscription?.cancel();
    _seriesSubscription?.cancel();
    _currentUserId = null;
    emit(const SermonInitial());
  }

  @override
  Future<void> close() {
    _notesSubscription?.cancel();
    _seriesSubscription?.cancel();
    return super.close();
  }
}
